### ISSUE TITLE
Prompt information

### ISSUE THREAD

**Issue by RichardoC** [hashishrajan/CloudGuardian#2]
Mind adding the prompt you're using to the repo, as well as the training data?

Thanks!

**Comment by hashishrajan** [comment]
Hi @RichardoC ! 

Thank you for your question. Currently, there seems to be no option for me to provide any additional prompts apart from describing the nature of the responses by the agent. I just updated the README for the limitation. I'm hoping as this is adopted more, there would be ability to do more than just say i want a friendly cloud security expert.

I will update this, when this changes.
